name: tinygram
description: A minimalistic yet capable wrapper for sending messages and files to Telegram via bot API.
version: 1.0.2
repository: https://github.com/4uzhoy/tinygram
issue_tracker: https://github.com/4uzhoy/tinygram/issues
homepage: https://github.com/4uzhoy/tinygram

environment:
  sdk: ^3.7.2

dependencies:
  http_parser: ^4.1.2 
  http: ^1.4.0
  mime: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
